apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "deployer.fullname" . }}
  labels:
{{ include "deployer.labels" . | nindent 4 }}
data:
  config.yaml: |
    {{ .Values.config | nindent 4 }}
