kind: ClusterRoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: {{ include "deployer.fullname" . }}
  labels:
{{ include "deployer.labels" . | indent 4 }}
subjects:
- kind: ServiceAccount
  name: {{ template "deployer.serviceAccountName" . }}
  namespace: {{ .Release.Namespace }}
roleRef:
  kind: ClusterRole
  name: {{ include "deployer.fullname" . }}
  apiGroup: rbac.authorization.k8s.io
