{{- if .Values.serviceAccount.create -}}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ template "deployer.serviceAccountName" . }}
  labels:
{{ include "deployer.labels" . | indent 4 }}
{{- end -}}
