version: 2
jobs:
  test:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout

      - run:
          name: install dependencies
          command: |
            go mod download

      - run:
          name: run tests
          command: go test -v ./...

      - run:
          name: lint code
          command: |
            curl -sfL https://install.goreleaser.com/github.com/golangci/golangci-lint.sh | sh -s -- -b $(go env GOPATH)/bin latest
            golangci-lint run

  build:
    docker:
      - image: circleci/golang:1.13

    steps:
      - checkout
      - setup_remote_docker

      - deploy:
          name: push docker images
          command: |
            [ "${CIRCLE_BRANCH}" != "master" ] && [ -z "${CIRCLE_TAG}" ] && exit 0

            export DOCKER_REPO=$(echo "${CIRCLE_PROJECT_USERNAME}/${CIRCLE_PROJECT_REPONAME}" | awk '{print tolower($0)}')

            docker login -u ${DOCKER_USER} -p "${DOCKER_PASS}" https://index.docker.io/v1/
            docker build -t ${DOCKER_REPO} .

            if [ "${CIRCLE_BRANCH}" == "master" ]; then
              docker push ${DOCKER_REPO}
            fi

            if [ -n "${CIRCLE_TAG}" ]; then
              docker tag ${DOCKER_REPO} ${DOCKER_REPO}:${CIRCLE_TAG}
              docker push ${DOCKER_REPO}:${CIRCLE_TAG}
            fi

  publish-chart:
    docker:
      - image: circleci/golang:1.13
    steps:
      - checkout
      - run:
          name: Replace version variables
          command: |
            sudo apt-get install gettext -y
            export REPLACE_TAG=$CIRCLE_TAG
            cat charts/deployer/Chart.yaml | envsubst '${REPLACE_TAG}' | tee charts/deployer/Chart.yaml
            cat charts/deployer/values.yaml | envsubst '${REPLACE_TAG}' | tee charts/deployer/values.yaml
      - run:
          name: helm-github-pages
          environment:
            GITHUB_PAGES_REPO: kubelix/helm-charts
            HELM_VERSION: 2.16.1
            CIRCLE_BRANCH: master
          command: wget -O - https://raw.githubusercontent.com/kubelix/helm-github-pages/master/publish.sh | bash

workflows:
  version: 2
  build:
    jobs:
      - test:
          filters:
            branches:
              only: /.*/
            tags:
              only: /.*/
      - build:
          requires:
            - test
          context: docker
          filters:
            branches:
              only: master
            tags:
              only: /.*/
      - publish-chart:
          requires:
            - build
          filters:
            branches:
              ignore: /.*/
            tags:
              only: /.*/
