apiVersion: apps.kubelix.io/v1alpha1
kind: Service
metadata:
  name: example
spec:
  singleton: false # implies replica = 1 & deployment strategy = recreate
  image: paulbouwer/hello-kubernetes:1.5 # {{ env "CI_COMMIT_SHA" | default "latest" }}
  serviceAccountName: ""

  ports:
    - name: http
      container: 8080
      service: 80
      ingresses:
        - host: "example.klinkert.io"

  resources:
    limits:
      cpu: "1"
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

  env:
    KEY1: VALUE1
    KEY2: value2

  files:
    - name: config
      path: /config.yaml
      content: |
        key: value
        map:
          something: different
