apiVersion: v1
kind: ConfigMap
metadata:
  name: deployer-config
  namespace: deployer
data:
  config.yaml: |
    ingress:
      annotations:
        cert-manager.io/cluster-issuer: letsencrypt
        kubernetes.io/ingress.class: nginx

    dockerPullSecretes:
      - registry: ${CI_REGISTRY}
        username: ${DOCKER_REGISTRY_USERNAME}
        password: ${DOCKER_REGISTRY_PASSWORD}
