on:
  push:
    branches:
      - master
    tags:
      - "*"

name: Build
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@master
      - name: Publish latest to Registry
        uses: HurricanKai/Publish-Docker-Github-Action@master
        with:
          name: kubelix/deployer
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}
          tagging: true
